"""two

Revision ID: 65d6471776f4
Revises: bdd4a2811b9a
Create Date: 2020-10-19 19:29:54.226252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d6471776f4'
down_revision = 'bdd4a2811b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
